Main dev
bx44/bootstrap-newsweek pull request #2
Opened 2020-01-15 20:13 UTC by bx44

This is the main development branch of the project, this is an initial pull request for a complete version of it.

2020-01-15 21:15 UTC, pelzolga123 commented on css/style.css
> +  /* margin-bottom: 25px; */
It's better to delete commented code.

2020-01-15 21:15 UTC, pelzolga123 requested changes
Project requires changes.

2020-01-15 21:16 UTC, pelzolga123 commented
## Hi Barak! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Your project looks :+1: greate!

Here what you need to change, before this project can be approved:
#### General
* [ ] Project should references [Bootstrap CSS file](https://getbootstrap.com/docs/4.3/getting-started/introduction/#css) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_requirement.png) from [Odin](https://www.theodinproject.com/courses/html5-and-css3/lessons/using-bootstrap)) Right now you just added this files to your project, that's not the right way.
* [ ] Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

#### Navbar
* [ ] It should contain Sign in and Subscribe links ([link to page](https://www.newsweek.com/))

#### Main content
* [ ] This section is missing:
![image](https://user-images.githubusercontent.com/20416431/72471434-561ffa80-37eb-11ea-9d4e-9abec3cc9d73.png)
* [ ] This part needs a little correction to look more like an original:
![image](https://user-images.githubusercontent.com/20416431/72471652-c2026300-37eb-11ea-88c8-b60605d36789.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/72471620-af882980-37eb-11ea-9ea3-a27b4d5ab31a.png)


#### Responsiveness
* [ ] Tablet version is messed a little:
![image](https://user-images.githubusercontent.com/20416431/72471899-33421600-37ec-11ea-8b0b-696fb4da54dd.png)

* [ ] In mobile version navbar is messed:
![image](https://user-images.githubusercontent.com/20416431/72472023-700e0d00-37ec-11ea-8e4d-eb751ce8cd2c.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-01-16 17:43 UTC, mosesogwo requested changes
### Hi @bx44 , good job. But we need to make some little changes for approval:
1. Sign in and Subscribe in the header should be links.
2. Align this section of the page properly:
> **Yours:** 
![image](https://user-images.githubusercontent.com/46611870/72548611-5376e100-388f-11ea-91b4-5c4d254be684.png)
> **Original:** 
![image](https://user-images.githubusercontent.com/46611870/72548663-70abaf80-388f-11ea-9b24-59954689f4e2.png)

**Kindly make these changes and submit another code review request**

### Status: Changes requested.

2020-01-16 20:21 UTC, mosesogwo approved these changes
### :trophy: Congratulations! Your project is approved.

You may now merge to master.

### Status: Approved!

2020-01-16 20:49 UTC, merged